before_install:
  - pip install --user codecov
  - sudo apt-get update
  - sudo apt-get install activemq
  - sudo /etc/init.d/activemq start
language: java
services:
  - rabbitmq
  - activemq
notifications:
  email: true
jdk:
  - oraclejdk8
#  - openjdk8
after_success:
  - codecov
