before_install:
  - pip install --user codecov
before_script:
  - src/test/resources/activemq.sh
language: java
services:
  - rabbitmq
notifications:
  email: true
jdk:
  - oraclejdk8
#  - openjdk8
after_success:
  - codecov
