development:
  rabbitmq:
    broker_uri: "failover:(tcp://localhost:61613?keepAlive=true)"
    preservation_destination: "/topic/event"

test:
  rabbitmq:
    broker_uri: "failover:(tcp://localhost:61613?keepAlive=true)"
    preservation_destination: "/topic/event"

