development:
  database_dir: src/test/resources/databasedir
  temporary_dir: src/test/resources/tmpdir	
  monitor_port: 2222	

test:
  database_dir: databasehome
  temporary_dir: temporarydir		
  monitor_port: 2222	

production: 
  database_dir: databasehome
  temporary_dir: temporarydir		
  monitor_port: 2222	

